branch-defaults:
  LiveTelemetryAWSbuild:
    environment: ava-production
global:
  application_name: ava-02-docker
  branch: null
  default_ec2_keyname: blakekey
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
